### ISSUE TITLE
test_speak.py is failing in CI

### ISSUE THREAD

**Issue by eeejay** [eeejay/spiel#27]
```
==================================== 5/11 ====================================
test:         test_speak.py
start time:   00:46:40
duration:     1.05s
result:       exit status 1
command:      SPIEL_TEST=1 GSETTINGS_SCHEMA_DIR=/workspaces/spiel/build/libspiel MALLOC_PERTURB_=126 TEST_SERVICE_DIR=/workspaces/spiel/build/tests/services LD_LIBRARY_PATH=/workspaces/spiel/build/libspiel:/workspaces/spiel/build/libspielprovider TEST_DISCARDED_SERVICE_DIR=/workspaces/spiel/build/tests/discarded_services GSETTINGS_BACKEND=memory G_DEBUG=fatal-warnings GI_TYPELIB_PATH=/workspaces/spiel/build/libspiel:/workspaces/spiel/build/libspielprovider /usr/bin/dbus-run-session --config-file=/workspaces/spiel/build/tests/test-bus.conf -- /usr/bin/python3 /workspaces/spiel/build/../tests/test_speak.py
----------------------------------- stdout -----------------------------------
# TAP results for TestSpeak
ok 1 test_cancel (__main__.TestSpeak.test_cancel)
ok 2 test_pause (__main__.TestSpeak.test_pause)
ok 3 test_pause_and_cancel (__main__.TestSpeak.test_pause_and_cancel)
not ok 4 test_pause_then_speak (__main__.TestSpeak.test_pause_then_speak)
# Traceback (most recent call last):
#   File "/usr/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
#     yield
#   File "/usr/lib/python3.11/unittest/case.py", line 623, in run
#     self._callTestMethod(testMethod)
#   File "/usr/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
#     if method() is not None:
#        ^^^^^^^^
#   File "/workspaces/spiel/build/../tests/test_speak.py", line 153, in test_pause_then_speak
#     self.assertEqual(actual_events, expected_events)
# AssertionError: Lists differ: [['notify:speaking', True], ['utterance-started', <[194 chars]lse]] != [['notify:paused', True], ['notify:paused', False],[245 chars]lse]]
# 
# First differing element 0:
# ['notify:speaking', True]
# ['notify:paused', True]
# 
# Second list contains 2 additional elements.
# First extra element 4:
# ['utterance-finished', <Spiel.Utterance object at 0x7f26e1a61980 (SpielUtterance at 0x1c195f0)>]
# 
# + [['notify:paused', True],
# +  ['notify:paused', False],
# - [['notify:speaking', True],
# ? ^
# 
# +  ['notify:speaking', True],
# ? ^
# 
#    ['utterance-started',
#     <Spiel.Utterance object at 0x7f26e1a61980 (SpielUtterance at 0x1c195f0)>],
#    ['utterance-finished',
#     <Spiel.Utterance object at 0x7f26e1a61980 (SpielUtterance at 0x1c195f0)>],
#    ['notify:speaking', False]]
ok 5 test_queue (__main__.TestSpeak.test_queue)
ok 6 test_speak (__main__.TestSpeak.test_speak)
1..6
----------------------------------- stderr -----------------------------------
dbus-daemon[5495]: [session uid=1000 pid=5495] Activating service name='org.mock.Speech.Provider' requested by ':1.0' (uid=1000 pid=5498 comm="/usr/bin/python3 /workspaces/spiel/build/../tests/" label="docker-default (enforce)")
dbus-daemon[5495]: [session uid=1000 pid=5495] Successfully activated service 'org.mock.Speech.Provider'
dbus-daemon[5495]: [session uid=1000 pid=5495] Activating service name='org.mock3.Speech.Provider' requested by ':1.2' (uid=1000 pid=5498 comm="/usr/bin/python3 /workspaces/spiel/build/../tests/" label="docker-default (enforce)")
dbus-daemon[5495]: [session uid=1000 pid=5495] Successfully activated service 'org.mock3.Speech.Provider'
dbus-daemon[5495]: [session uid=1000 pid=5495] Activating service name='org.mock2.Speech.Provider' requested by ':1.2' (uid=1000 pid=5498 comm="/usr/bin/python3 /workspaces/spiel/build/../tests/" label="docker-default (enforce)")
dbus-daemon[5495]: [session uid=1000 pid=5495] Successfully activated service 'org.mock2.Speech.Provider'

(test program exited with status code 1)
==============================================================================
```

**Comment by eeejay** [comment]
Fixed
