### ISSUE TITLE
Crash in `spiel_speaker_cancel()` with espeak

### ISSUE THREAD

**Issue by andyholmes** [eeejay/spiel#29]
While testing with the spiel-demos/espeak, I encountered this crash. I'm not familiar enough with the direct audio code to follow it into GStreamer unfortunately :/

```c
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007f5136cae8a3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007f5136c5c8ee in __GI_raise (sig=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f5136c5c9a0 in <signal handler called> () at /lib64/libc.so.6
#4  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#5  0x00007f5136cae8a3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#6  0x00007f5136c5c8ee in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#7  0x00007f5136c448ff in __GI_abort () at abort.c:79
#8  0x00007f510c1a7435 in pa_close_pipe (fds=fds@entry=0x558b00a39490) at ../src/pulsecore/core-util.c:2713
#9  0x00007f510c22182e in pa_mainloop_free (m=0x558b00a393c0) at ../src/pulse/mainloop.c:594
#10 0x00007f510c23a979 in pa_threaded_mainloop_free (m=0x558b00a14610) at ../src/pulse/thread-mainloop.c:138
#11 0x00007f510c26ea60 in gst_pulsesink_release_mainloop (psink=0x558b00aa8d30 [GstPulseSink]) at ../ext/pulse/pulsesink.c:3228
#12 gst_pulsesink_release_mainloop (psink=psink@entry=0x558b00aa8d30 [GstPulseSink]) at ../ext/pulse/pulsesink.c:3211
#13 0x00007f510c26ec20 in gst_pulsesink_change_state (element=0x558b00aa8d30 [GstPulseSink], transition=GST_STATE_CHANGE_READY_TO_NULL) at ../ext/pulse/pulsesink.c:3281
#14 0x00007f510de2da94 in gst_element_change_state (element=element@entry=0x558b00aa8d30 [GstPulseSink], transition=transition@entry=GST_STATE_CHANGE_READY_TO_NULL) at ../gst/gstelement.c:3093
#15 0x00007f510de2e349 in gst_element_set_state_func (element=0x558b00aa8d30 [GstPulseSink], state=GST_STATE_NULL) at ../gst/gstelement.c:3047
#16 0x00007f510de05488 in gst_bin_element_set_state (next=<optimized out>, current=<optimized out>, start_time=0 [0:00:00.000000000], base_time=672000 [0:00:00.000672000], element=0x558b00aa8d30 [GstPulseSink], bin=<optimized out>)
    at ../gst/gstbin.c:2582
#17 gst_bin_change_state_func (element=0x558affd3b9c0 [GstAutoAudioSink], transition=GST_STATE_CHANGE_READY_TO_NULL) at ../gst/gstbin.c:2931
#18 0x00007f5124004dc6 in gst_auto_detect_change_state (element=0x558affd3b9c0 [GstAutoAudioSink], transition=<optimized out>) at ../gst/autodetect/gstautodetect.c:427
#19 0x00007f510de2da94 in gst_element_change_state (element=element@entry=0x558affd3b9c0 [GstAutoAudioSink], transition=transition@entry=GST_STATE_CHANGE_READY_TO_NULL) at ../gst/gstelement.c:3093
#20 0x00007f510de2e349 in gst_element_set_state_func (element=0x558affd3b9c0 [GstAutoAudioSink], state=GST_STATE_NULL) at ../gst/gstelement.c:3047
#21 0x00007f510de05488 in gst_bin_element_set_state (next=<optimized out>, current=<optimized out>, start_time=0 [0:00:00.000000000], base_time=672000 [0:00:00.000672000], element=0x558affd3b9c0 [GstAutoAudioSink], bin=<optimized out>)
    at ../gst/gstbin.c:2582
#22 gst_bin_change_state_func (element=0x558b00befda0 [GstPipeline], transition=GST_STATE_CHANGE_READY_TO_NULL) at ../gst/gstbin.c:2931
#23 0x00007f510de5878a in gst_pipeline_change_state (element=0x558b00befda0 [GstPipeline], transition=GST_STATE_CHANGE_READY_TO_NULL) at ../gst/gstpipeline.c:529
#24 0x00007f510de2da94 in gst_element_change_state (element=element@entry=0x558b00befda0 [GstPipeline], transition=GST_STATE_CHANGE_READY_TO_NULL) at ../gst/gstelement.c:3093
#25 0x00007f510de2e001 in gst_element_continue_state (element=element@entry=0x558b00befda0 [GstPipeline], ret=ret@entry=GST_STATE_CHANGE_SUCCESS) at ../gst/gstelement.c:2801
#26 0x00007f510de2dad8 in gst_element_change_state (element=element@entry=0x558b00befda0 [GstPipeline], transition=<optimized out>) at ../gst/gstelement.c:3132
#27 0x00007f510de2e001 in gst_element_continue_state (element=element@entry=0x558b00befda0 [GstPipeline], ret=ret@entry=GST_STATE_CHANGE_SUCCESS) at ../gst/gstelement.c:2801
#28 0x00007f510de2dad8 in gst_element_change_state (element=element@entry=0x558b00befda0 [GstPipeline], transition=transition@entry=GST_STATE_CHANGE_PLAYING_TO_PAUSED) at ../gst/gstelement.c:3132
#29 0x00007f510de2e349 in gst_element_set_state_func (element=0x558b00befda0 [GstPipeline], state=GST_STATE_NULL) at ../gst/gstelement.c:3047
#30 0x00007f510c40fa3b in _advance_to_next_entry_or_finish (self=0x558b000644b0 [SpielSpeaker], canceled=1) at ../libspiel/spiel-speaker.c:996
#31 0x00007f510c40f02e in spiel_speaker_cancel (self=0x558b000644b0 [SpielSpeaker]) at ../libspiel/spiel-speaker.c:786
#32 0x00007f5136c17056 in ffi_call_unix64 () at ../src/x86/unix64.S:104
#33 0x00007f5136c135ef in ffi_call_int (cif=cif@entry=0x558b00120518, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>, closure=closure@entry=0x0) at ../src/x86/ffi64.c:673
#34 0x00007f5136c163fe in ffi_call (cif=cif@entry=0x558b00120518, fn=<optimized out>, rvalue=rvalue@entry=0x7ffc78a5a228, avalue=<optimized out>) at ../src/x86/ffi64.c:710
#35 0x00007f51374babdb in pygi_invoke_c_callable (function_cache=0x558b00120470, state=<optimized out>, py_args=<optimized out>, py_kwargs=<optimized out>) at ../gi/pygi-invoke.c:684
#36 0x00007f51374b912a in pygi_function_cache_invoke (py_kwargs=0x0, py_args=0x7f50f9c0cee0, function_cache=<optimized out>) at ../gi/pygi-cache.c:862
#37 pygi_callable_info_invoke (user_data=0x0, cache=<optimized out>, kwargs=0x0, py_args=0x7f50f9c0cee0, info=<optimized out>) at ../gi/pygi-invoke.c:727
#38 _wrap_g_callable_info_invoke (self=<optimized out>, py_args=0x7f50f9c0cee0, kwargs=0x0) at ../gi/pygi-invoke.c:764
#39 0x00007f51374ab66f in _callable_info_call (kwargs=0x0, args=0x7f51373f0cc8 <_PyRuntime+76264>, self=0x7f510d5c94f0) at ../gi/pygi-info.c:548
#40 _callable_info_call (self=0x7f510d5c94f0, args=0x7f51373f0cc8 <_PyRuntime+76264>, kwargs=0x0) at ../gi/pygi-info.c:525
#41 0x00007f5136ff7156 in _PyObject_MakeTpCall (tstate=0x7f513744e668 <_PyRuntime+459656>, callable=0x7f510d5c94f0, args=0x7f51374e1960, nargs=0, keywords=0x0) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Objects/call.c:240
#42 0x00007f5136f0f75a in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=0x7f51374e1900, throwflag=<optimized out>) at Python/bytecodes.c:2706
#43 0x00007f5137035346 in _PyFunction_Vectorcall (kwnames=0x0, nargsf=1, stack=0x7ffc78a5a5d8, func=0x7f51242594e0) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Objects/call.c:419
#44 _PyObject_VectorcallTstate (kwnames=0x0, nargsf=1, args=0x7ffc78a5a5d8, callable=0x7f51242594e0, tstate=0x7f513744e668 <_PyRuntime+459656>) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Include/internal/pycore_call.h:92
#45 method_vectorcall (method=<optimized out>, args=0x7f51373f0ce0 <_PyRuntime+76288>, nargsf=0, kwnames=0x0) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Objects/classobject.c:69
#46 0x00007f51374b9802 in _pygi_closure_handle (cif=<optimized out>, result=<optimized out>, args=<optimized out>, data=<optimized out>) at ../gi/pygi-closure.c:582
#47 0x00007f5136c16a81 in ffi_closure_unix64_inner (cif=<optimized out>, fun=<optimized out>, user_data=<optimized out>, rvalue=<optimized out>, reg_args=<optimized out>, argp=0x7ffc78a5a910 "") at ../src/x86/ffi64.c:899
#48 0x00007f5136c17278 in ffi_closure_unix64 () at ../src/x86/unix64.S:303
#49 0x00007f512920e78d in g_idle_dispatch (source=0x558b0043ab70, callback=0x7f51279d8f28, user_data=0x558b0026c950) at ../glib/gmain.c:6282
#50 0x00007f5129211e5c in g_main_dispatch (context=0x558aff582180) at ../glib/gmain.c:3476
#51 g_main_context_dispatch_unlocked (context=0x558aff582180) at ../glib/gmain.c:4284
#52 0x00007f512926cf18 in g_main_context_iterate_unlocked.isra.0 (context=0x558aff582180, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4349
#53 0x00007f5129213447 in g_main_loop_run (loop=0x558b009e7880) at ../glib/gmain.c:4551
#54 0x00007f51279b13b8 in atspi_event_main () at ../atspi/atspi-misc.c:1124
#55 0x00007f5136c17056 in ffi_call_unix64 () at ../src/x86/unix64.S:104
#56 0x00007f5136c135ef in ffi_call_int (cif=cif@entry=0x558b009e7668, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>, closure=closure@entry=0x0) at ../src/x86/ffi64.c:673
#57 0x00007f5136c163fe in ffi_call (cif=cif@entry=0x558b009e7668, fn=<optimized out>, rvalue=rvalue@entry=0x7ffc78a5acb8, avalue=<optimized out>) at ../src/x86/ffi64.c:710
#58 0x00007f51374babdb in pygi_invoke_c_callable (function_cache=0x558b009e75c0, state=<optimized out>, py_args=<optimized out>, py_kwargs=<optimized out>) at ../gi/pygi-invoke.c:684
#59 0x00007f51374b912a in pygi_function_cache_invoke (py_kwargs=0x0, py_args=0x7f51373f0cc8 <_PyRuntime+76264>, function_cache=<optimized out>) at ../gi/pygi-cache.c:862
#60 pygi_callable_info_invoke (user_data=0x0, cache=<optimized out>, kwargs=0x0, py_args=0x7f51373f0cc8 <_PyRuntime+76264>, info=<optimized out>) at ../gi/pygi-invoke.c:727
#61 _wrap_g_callable_info_invoke (self=<optimized out>, py_args=0x7f51373f0cc8 <_PyRuntime+76264>, kwargs=0x0) at ../gi/pygi-invoke.c:764
#62 0x00007f5136ff7156 in _PyObject_MakeTpCall (tstate=0x7f513744e668 <_PyRuntime+459656>, callable=0x7f510dc94630, args=0x7f51374e1270, nargs=0, keywords=0x0) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Objects/call.c:240
#63 0x00007f5136f0f75a in _PyEval_EvalFrameDefault (tstate=<optimized out>, frame=0x7f51374e1200, throwflag=<optimized out>) at Python/bytecodes.c:2706
#64 0x00007f513708b196 in PyEval_EvalCode (co=0x558aff2906c0, globals=<optimized out>, locals=0x7f51295f9ac0) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/ceval.c:578
#65 0x00007f51370add5a in run_eval_code_obj (tstate=tstate@entry=0x7f513744e668 <_PyRuntime+459656>, co=co@entry=0x558aff2906c0, globals=globals@entry=0x7f51295f9ac0, locals=locals@entry=0x7f51295f9ac0)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/pythonrun.c:1691
#66 0x00007f51370a8cce in run_mod
    (mod=mod@entry=0x558aff32e1b8, filename=filename@entry=0x7f5129423bf0, globals=globals@entry=0x7f51295f9ac0, locals=locals@entry=0x7f51295f9ac0, flags=flags@entry=0x7ffc78a5b260, arena=arena@entry=0x7f512951be70)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/pythonrun.c:1712
#67 0x00007f51370c97a3 in pyrun_file
    (fp=fp@entry=0x558aff236b30, filename=filename@entry=0x7f5129423bf0, start=start@entry=257, globals=globals@entry=0x7f51295f9ac0, locals=locals@entry=0x7f51295f9ac0, closeit=closeit@entry=1, flags=0x7ffc78a5b260)
    at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/pythonrun.c:1612
#68 0x00007f51370c8afa in _PyRun_SimpleFileObject (fp=0x558aff236b30, filename=0x7f5129423bf0, closeit=1, flags=0x7ffc78a5b260) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/pythonrun.c:433
#69 0x00007f51370c888f in _PyRun_AnyFileObject (fp=0x558aff236b30, filename=0x7f5129423bf0, closeit=1, flags=0x7ffc78a5b260) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Python/pythonrun.c:78
#70 0x00007f51370b9632 in pymain_run_file_obj (skip_source_first_line=0, filename=0x7f5129423bf0, program_name=0x7f51294238b0) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Modules/main.c:360
#71 pymain_run_file (config=0x7f51373f1248 <_PyRuntime+77672>) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Modules/main.c:379
#72 pymain_run_python (exitcode=0x7ffc78a5b234) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Modules/main.c:629
#73 Py_RunMain () at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Modules/main.c:709
#74 0x00007f5137074f5c in Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/python3.12-3.12.1-2.fc39.x86_64/Modules/main.c:763
#75 0x00007f5136c4614a in __libc_start_call_main (main=main@entry=0x558afdec8160 <main>, argc=argc@entry=4, argv=argv@entry=0x7ffc78a5b4c8) at ../sysdeps/nptl/libc_start_call_main.h:58
#76 0x00007f5136c4620b in __libc_start_main_impl (main=0x558afdec8160 <main>, argc=4, argv=0x7ffc78a5b4c8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc78a5b4b8) at ../csu/libc-start.c:360
#77 0x0000558afdec8095 in _start ()
```

**Comment by eeejay** [comment]
Can you attach a snippet of code that causes this crash?

**Comment by andyholmes** [comment]
Here's what I've come up with so far. If the start time is not offset enough (relative to length?) then spiel will hit a crash starting with tons of broken pipe warnings:

```
pa_write() failed while trying to wake up the mainloop: Broken pipe
pa_write() failed while trying to wake up the mainloop: Broken pipe
pa_write() failed while trying to wake up the mainloop: Broken pipe
Assertion 'pa_close(fds[0]) == 0' failed at ../src/pulsecore/core-util.c:2713, function pa_close_pipe(). Aborting.
```

If it's offset enough then it will not crash but does log the same mainloop/pipe errors. Here is a copy-paste snippet:


```python3
import sys

import gi
gi.require_version('Spiel', '0.1')
from gi.repository import GLib, Spiel

if __name__ == "__main__":
    loop = GLib.MainLoop()
    speaker = Spiel.Speaker.new_sync(None)
    voice = None

    # Grab the standard espeak voice
    for entry in speaker.props.voices:
        if entry.props.provider_name != "org.espeak.Speech.Provider":
            continue
        if entry.props.name != "English (America)":
            continue
        voice = entry

    # Queue/Defer some utterances
    for i in range(10):
        utterance = Spiel.Utterance(text="OK boomer", voice=voice)
        GLib.timeout_add(i * 100, lambda: speaker.speak(utterance))

    try:
        loop.run()
    except KeyboardInterrupt:
        speaker.cancel()
        #loop.quit()

    sys.exit(0)
```
